SELECT 
FST.ID_FLEX_STRUCTURE_NAME,
R.FLEX_VALIDATION_RULE_NAME,
R.ENABLED_FLAG,
L.ENABLED_FLAG,
L.INCLUDE_EXCLUDE_INDICATOR "INC?",
L.CONCATENATED_SEGMENTS_LOW "FROM",
L.CONCATENATED_SEGMENTS_HIGH "TO",
L.LAST_UPDATED_BY,
L.LAST_UPDATE_DATE
FROM
FND_FLEX_VALIDATION_RULES R,
FND_FLEX_VDATION_RULES_TL TL,
FND_FLEX_VALIDATION_RULE_LINES L,
FND_ID_FLEX_STRUCTURES_VL FST
WHERE 1=1 AND
R.APPLICATION_ID = TL.APPLICATION_ID
AND
FST.ID_FLEX_NUM = R.ID_FLEX_NUM
AND
R.ID_FLEX_CODE = TL.ID_FLEX_CODE
AND
R.ID_FLEX_NUM = TL.ID_FLEX_NUM
AND
R.FLEX_VALIDATION_RULE_NAME = TL.FLEX_VALIDATION_RULE_NAME
AND
R.FLEX_VALIDATION_RULE_NAME = TL.FLEX_VALIDATION_RULE_NAME
AND
R.APPLICATION_ID = L.APPLICATION_ID
AND
R.ID_FLEX_CODE = L.ID_FLEX_CODE
AND
R.ID_FLEX_NUM = L.ID_FLEX_NUM
AND
R.FLEX_VALIDATION_RULE_NAME = L.FLEX_VALIDATION_RULE_NAME
AND
R.FLEX_VALIDATION_RULE_NAME = L.FLEX_VALIDATION_RULE_NAME
AND
R.APPLICATION_ID = 101
ORDER BY 1,R.FLEX_VALIDATION_RULE_NAME, L.INCLUDE_EXCLUDE_INDICATOR DESC, L.CONCATENATED_SEGMENTS_LOW